import { Chart, Overview } from 'components'
import Head from 'next/head'
import React from 'react'
import { Footer, Navbar } from 'templates'

export default function Home() {
  return (
    <React.Fragment>
        <Head>
          <title>Keyri`s</title> 
          <meta name='description' content='Generated by created next app'/>
        </Head>
        <Navbar/>
          {/* <Overview/> */}
          <Chart/>
        <Footer/>
    </React.Fragment>

    dev
    feature/dashboard-admin
    hotfix/dashboard-admin
    staging
  )
}
